package com.butler.launcher.utils;

import java.util.HashSet;

public class LauncherUtils {

    public static HashSet<String> getAppFifter() {
        HashSet<String> appHashSet = new HashSet<>();
        for (int i = 0; i < filterAppPackageName.length; i++) {
            appHashSet.add(filterAppPackageName[i]);
        }
        return appHashSet;
    }

    //需要屏蔽的apk
    private static String[] filterAppPackageName = {
            "com.butler.launcher",
            "com.android.wallpaperpicker",
            "com.android.backupconfirm",
            "android.ext.shared",
            "com.android.mtp",
            "com.android.shell",
            "com.android.proxyhandler",
            "com.android.managedprovisioning",
            "com.google.android.feedback",
            "com.android.inputdevices",
            "com.android.keychain",
            "com.android.printspooler",
            "com.android.onetimeinitializer",
            "com.android.smspush",
            "com.android.inputmethod.latin",
            "com.android.printservice.recommendation",
            "com.android.dreams.basic",
            "com.zyw.horrarndoo.nestingrecyclerviewdemo",
            "com.android.provision",
            "com.android.defcontainer",
            "com.android.cts.priv.ctsshim",
            "com.android.apkinstaller",
            "com.android.certinstaller",
            "android",
            "com.android.packageinstaller",
            "com.android.providers.downloads.ui",
            "com.android.externalstorage",
            "com.android.providers.userdictionary",
            "com.android.dreams.phototable",
            "com.android.proxyhandler",
            "com.android.wallpaperbackup",
            "com.google.android.feedback",
            "com.google.android.onetimeinitializer",
            "com.android.wallpaper.livepicker",
            "com.android.printspooler",
            "com.android.bluetooth",
            "com.android.onetimeinitializer",
            "com.android.smspush",
            "com.android.inputmethod.latin",
            "com.android.printservice.recommendation",
            "com.android.dreams.basic",
            "com.android.contacts",
            "com.android.vpndialogs",
            "com.android.server.telecom",
            "com.DeviceTest",
            "com.butler.launcher",
            "com.android.defcontainer",
            "com.android.cts.priv.ctsshim",
            "com.android.quicksearchbox",
            "com.android.systemui",
            "com.android.phone",
            "com.android.providers.calendar",
            "com.android.certinstaller",
            "com.android.webview",
            "com.android.providers.telephony",
            "com.android.providers.blockednumber",
            "com.android.providers.downloads",
            "com.google.android.gsf",
            "com.android.htmlviewer",
            "com.android.bookmarkprovider",
            "com.android.location.fused",
            "jp.co.omronsoft.openwnn",
            "com.android.providers.contacts",
            "com.android.bluetoothmidiservice",
            "com.cghs.stresstest",
            "com.android.cts.ctsshim",
            "com.android.settings",
            "com.android.sharedstoragebackup",
            "com.android.wallpapercropper",
            "com.svox.pico",
            "com.android.rk.mediafloat",
            "com.android.providers.settings",
            "com.android.captiveportallogin",
            "com.google.android.gms",
            "com.google.android.backuptransport",
            "com.android.statementservice",
            "android.rockchip.update.service",
            "android.ext.services",
            "com.android.pacprocessor",
            "com.android.launcher",
            "com.android.wallpaper.holospiral",
            "com.android.retaildemo",
            "com.android.mms.service",
            "com.google.android.inputmethod.pinyin",
            "com.android.providers.media",
            "com.android.musicfx",
            "com.android.egg",
            "com.google.android.partnersetup",
            "com.android.storagemanager",
            "com.google.android.gsf.login"
    };
}
