package com.butler.launcher.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.butler.launcher.db.event.AppLayoutEvent;

import com.butler.launcher.db.dao.AppLayoutEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appLayoutEventDaoConfig;

    private final AppLayoutEventDao appLayoutEventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appLayoutEventDaoConfig = daoConfigMap.get(AppLayoutEventDao.class).clone();
        appLayoutEventDaoConfig.initIdentityScope(type);

        appLayoutEventDao = new AppLayoutEventDao(appLayoutEventDaoConfig, this);

        registerDao(AppLayoutEvent.class, appLayoutEventDao);
    }
    
    public void clear() {
        appLayoutEventDaoConfig.clearIdentityScope();
    }

    public AppLayoutEventDao getAppLayoutEventDao() {
        return appLayoutEventDao;
    }

}
